version: 0.2
phases:

  install:
    commands:
     - cd infra
     - npm install
     - echo "Install testing framework here"
  pre_build:
    commands:
     - npm install -g aws-cdk

  build:
    commands:
      - cdk deploy S3Stack --require-approval=never --verbose
      - cdk deploy BackendStack --require-approval=never --verbose

artifacts:
  files: "**/*"