version: 0.2
phases:
  install:
    commands:
     - pip install awscli
  build:
    commands:
     - aws s3 sync ./lib/Site/ s3://${HOSTING_BUCKET}
     - aws s3 sync ./lib/data/ s3://${HOSTING_BUCKET}/data
  post_build:
    commands:
      - echo "post build actions here"