version: 0.2
phases:

  install:
    commands:
     - cd ts-infra
     - npm install
     - echo "Install testing framework here"
  pre_build:
    commands:
     - npm install -g aws-cdk

  build:
    commands:
      - cdk synth
#      - cdk deploy S3Stack --require-approval=never --verbose
#      - cdk deploy backendStack --require-approval=never --verbose

  artifacts:
    base-directory: cdk.out
    files: "**/*"