version: 0.2
phases:

  install:
    commands:
     - cd ts-infra
     - npm install
  pre_build:
    commands:
     - npm install -g aws-cdk

  build:
    commands:
      - cdk deploy backendStack --require-approval=never --verbose