version: 0.2
phases:
  install:
    commands:
     - pip install awscli
  build:
    commands:
     - aws s3 sync ./lib/Site/s3://${HOSTING_BUCKET}
  post_build:
    commands:
      - echo "post build actions here"